name: Scrape Lottery Data

on:
  schedule:
    # 每天台灣時間 21:00 (UTC+8) = UTC 13:00 執行
    - cron: '0 13 * * *'
  workflow_dispatch: # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run scraper
      run: |
        python scraper.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lottery_data.json
        git diff --staged --quiet || git commit -m "Update lottery data - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}